name: Verible linter
on:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: chipsalliance/verible-linter-action@main
      with:
        paths: |
              ./source
        exclude_paths: |
          ./ice40
        extra_args: "--check_syntax=true --module-filename=false"
        verible_version: "v0.0-3100-gd75b1c47"
        extensions: |
          .sv
          .v
          .vh
          .svh
        github_token: ${{ secrets.GITHUB_TOKEN }}
